"""Central configuration and public protocol limits."""

HOST = "127.0.0.1"
PORT = 19281
PLUGIN_VERSION = "1.1.1"
PROTOCOL_VERSION = "1.0"

SPEECH_BUFFER_SIZE = 100
EVENT_BUFFER_SIZE = 500
MAX_EVENT_TEXT = 8192
MAX_OBJECT_TEXT = 8192

DEFAULT_TREE_DEPTH = 3
DEFAULT_TREE_CHILDREN = 20
DEFAULT_TREE_NODES = 200
DEFAULT_TREE_TIMEOUT_MS = 500

# A larger request must use the asynchronous export API. These are safety
# limits, not claims that a single COM call can be interrupted at the limit.
SYNC_MAX_DEPTH = 10
SYNC_MAX_CHILDREN = 200
SYNC_MAX_NODES = 1000
SYNC_MAX_TIMEOUT_MS = 3000
SYNC_BATCH_NODES = 25
SYNC_BATCH_BUDGET_MS = 20
MAX_CONCURRENT_SYNC_TREES = 2
SYNC_MAX_RESULT_BYTES = 2 * 1024 * 1024

DEFAULT_FIELDS = (
	"name",
	"role",
	"states",
	"value",
	"description",
	"className",
	"appName",
)
ALLOWED_FIELDS = DEFAULT_FIELDS + ("location", "windowText")
ROOT_NAMES = ("focus", "foreground", "navigator", "desktop")
TREE_FORMATS = ("nested", "flat")

OBJECT_TTL_SECONDS = 30.0
OBJECT_REGISTRY_CAPACITY = 5000

EXPORT_BATCH_NODES = 25
EXPORT_BATCH_BUDGET_MS = 20
EXPORT_BATCH_CALL_TIMEOUT_MS = 5000
EXPORT_MAX_CONCURRENT = 1
EXPORT_MAX_DEPTH = 100
EXPORT_MAX_CHILDREN = 10000
EXPORT_MAX_NODES = 1000000
EXPORT_MAX_DURATION_SECONDS = 300.0
EXPORT_MAX_BYTES = 100 * 1024 * 1024
EXPORT_MAX_TOTAL_BYTES = 200 * 1024 * 1024
EXPORT_MAX_RETAINED_JOBS = 8
EXPORT_CREATE_RATE_LIMIT = 10
EXPORT_CREATE_RATE_WINDOW_SECONDS = 60.0
EXPORT_TTL_SECONDS = 600.0
EXPORT_REAPER_INTERVAL_SECONDS = 30.0
EXPORT_DIRECTORY_NAME = "nvda-http-bridge"

BACKUP_MAX_CONCURRENT = 1
BACKUP_MAX_DURATION_SECONDS = 600.0
BACKUP_MAX_BYTES = 2 * 1024 * 1024 * 1024
BACKUP_CREATE_RATE_LIMIT = 2
BACKUP_CREATE_RATE_WINDOW_SECONDS = 60.0
BACKUP_TTL_SECONDS = 600.0
BACKUP_REAPER_INTERVAL_SECONDS = 30.0

MAX_REQUEST_BODY = 256 * 1024
MAX_HEADER_BYTES = 32 * 1024
MAX_REQUEST_LINE_BYTES = 8 * 1024
MAX_CONNECTIONS = 12
MAX_ACTIVE_REQUESTS = 8
MAX_SSE_CLIENTS = 2
SOCKET_TIMEOUT_SECONDS = 5.0
SERVER_JOIN_TIMEOUT_SECONDS = 3.0

TOKEN_FILE_NAME = "nvdaHttpBridge.token"
REQUIRE_READ_TOKEN = False

# These gestures can terminate or reload the plugin while its own HTTP
# request is still in flight. Modifier order is normalized by the service.
BLOCKED_GESTURE_CHORDS = (
	("nvda", "control", "f3"),
	("nvda", "q"),
)
